### ISSUE TITLE
Vimeo videos accept no options, shows no controls by default.

### ISSUE THREAD

**Issue by davidohlin** [streamich/react-embed#267]
Hi!

I'm trying to embed a video from Vimeo like this:

```jsx
<Embed url="https://vimeo.com/391449909" />
```

This will only display a static preview image of the video without controls, meaning there is no way to  play the video. 

 [React Player accepts props](https://github.com/CookPete/react-player#props) to display native player controls, set video volume etc. 

I think you should be able to pass props and parse them in the `react-player` block, so that usage looks something like this:
```jsx
<Embed url="https://vimeo.com/391449909" controls={true} volume={1} />
// OR
<Embed url="https://vimeo.com/391449909" options={{ controls: true, volume: 1 }} />
```

**Comment by streamich** [comment]
This should be fixed now. Controls should be visible now, but no extra props can be passed to `react-player`.
