### ISSUE TITLE
Styling embeds

### ISSUE THREAD

**Issue by iwatakeshi** [streamich/react-embed#320]
Hi. I'm trying to center an embedded tweet but can't seem to get it to work. I looked into the code and noticed that [the margin is using `!important`](https://github.com/streamich/react-embed/blob/88f5810d3e6b64bd01bf197014ae3200eb3d3661/src/blocks/tweet/index.tsx#L8) which makes it difficult to override. Is there a way to override this or properly style the embeds?

Thank you

**Comment by streamich** [comment]
You should be able to center it using Flexbox, with something like this:

```jsx
<div style={{display: 'flex', justifyContent: 'center', width: '100%'}}>
  <Embed src={'...'} />
</div>
```
