### ISSUE TITLE
Check for valid URL

### ISSUE THREAD

**Issue by joaomarceloods** [streamich/react-embed#627]
Hi, is there a way to check whether a URL is supported?

Use case: the user enters a URL, if it's supported the app adds an Embed component, else it displays a feedback message.

Currently, if you provide an unsupported URL to Embed, it simply renders null.

This is my current workaround to check whether Embed supports the URL, but I'm afraid it's a bit hackish, as it relies on defaultProps (it wouldn't catch additional props):

```typescript
import { ParsedUrl, ReactEmbed } from 'react-embed'

function isUrlSupported(url: string): boolean {
  const { blocks, router } = ReactEmbed.defaultProps
  const routerResult = router(blocks, getParsedUrl(url))
  return Boolean(routerResult)
}

function getParsedUrl(rawUrl: string): ParsedUrl {
  const url = new URL(rawUrl)
  const { hostname, pathname, search, hash } = url
  return {
    url: rawUrl,
    hostname,
    pathname,
    search,
    hash,
  }
}

```

**Comment by mledwards** [comment]
There's a list at the bottom of the [README](https://github.com/streamich/react-embed#----supported--) file. You could go get the URLs for each of them, put them in an array and test if the passed URL appears in the list?

**Comment by streamich** [comment]
Haven't checked it, but I believe you should be able to use the `renderVoid` prop, to render whatever you want in case the component cannot figure out what to render.

---

Alternatively, there is [`routeToBlock` function](https://github.com/streamich/react-embed/blob/master/src/routeToBlock.ts#L64), which tries to figure out which component to use to render the content. You could use that, to see which component `react-embed` will try to use to render your URL.
